/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormMahasiswa;

/**
 *
 * @author Acer
 */
public class FormMahasiswa extends javax.swing.JFrame {
 String namaMhs, nim, jk, agama, tlp,  minat;
    public FormMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        aluminiumDefaultTheme1 = new com.jtattoo.plaf.aluminium.AluminiumDefaultTheme();
        aluminiumLookAndFeel1 = new com.jtattoo.plaf.aluminium.AluminiumLookAndFeel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TOutput = new javax.swing.JTextArea();
        CmbProgramStudi = new javax.swing.JComboBox<>();
        BProses = new javax.swing.JButton();
        CNetworking = new javax.swing.JCheckBox();
        CMultimedia = new javax.swing.JCheckBox();
        CProgrammer = new javax.swing.JCheckBox();
        CDesain = new javax.swing.JCheckBox();
        RBWanita = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        TNama = new javax.swing.JTextField();
        BKeluar = new javax.swing.JButton();
        Nama = new javax.swing.JLabel();
        RBPria = new javax.swing.JRadioButton();
        TNim = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Hp = new javax.swing.JLabel();
        Nim = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        THp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CmbDaerahAsal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 204));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FORM MAHASISWA");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        TOutput.setColumns(20);
        TOutput.setRows(5);
        jScrollPane1.setViewportView(TOutput);

        CmbProgramStudi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Komputer", "S1 Teknik Informasi", "S1 Teknik Informatika" }));
        CmbProgramStudi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CmbProgramStudiMouseClicked(evt);
            }
        });
        CmbProgramStudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbProgramStudiActionPerformed(evt);
            }
        });

        BProses.setText("Proses");
        BProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BProsesActionPerformed(evt);
            }
        });

        CNetworking.setBackground(new java.awt.Color(255, 204, 204));
        CNetworking.setForeground(new java.awt.Color(204, 204, 204));
        CNetworking.setText("Networking");

        CMultimedia.setBackground(new java.awt.Color(255, 204, 204));
        CMultimedia.setForeground(new java.awt.Color(204, 204, 204));
        CMultimedia.setText("Multimedia");

        CProgrammer.setBackground(new java.awt.Color(255, 204, 204));
        CProgrammer.setForeground(new java.awt.Color(204, 204, 204));
        CProgrammer.setText("Programmer");
        CProgrammer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CProgrammerActionPerformed(evt);
            }
        });

        CDesain.setBackground(new java.awt.Color(255, 204, 204));
        CDesain.setForeground(new java.awt.Color(204, 204, 204));
        CDesain.setText("Desain Grafis");

        RBWanita.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(RBWanita);
        RBWanita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RBWanita.setForeground(new java.awt.Color(255, 204, 204));
        RBWanita.setText("Perempuan");
        RBWanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBWanitaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Minat");

        TNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNamaActionPerformed(evt);
            }
        });

        BKeluar.setText("KELUAR");
        BKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKeluarActionPerformed(evt);
            }
        });

        Nama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nama.setForeground(new java.awt.Color(255, 255, 255));
        Nama.setText("Nama ");

        RBPria.setBackground(new java.awt.Color(255, 255, 255));
        gender.add(RBPria);
        RBPria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RBPria.setForeground(new java.awt.Color(255, 204, 204));
        RBPria.setText("Laki-Laki");
        RBPria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBPriaActionPerformed(evt);
            }
        });

        TNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNimActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Program Studi");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        Hp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Hp.setForeground(new java.awt.Color(255, 255, 255));
        Hp.setText("Tlp / Hp");

        Nim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nim.setForeground(new java.awt.Color(255, 255, 255));
        Nim.setText("Nomor Induk");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");

        THp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THpActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Daerah Asal");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        CmbDaerahAsal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samarinda ", "Tenggarong", "Balikpapan ", "Bontang", "Sangatta" }));
        CmbDaerahAsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbDaerahAsalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBPria)
                            .addComponent(RBWanita)
                            .addComponent(jLabel5))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(CDesain)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CMultimedia))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(CProgrammer)
                                    .addGap(30, 30, 30)
                                    .addComponent(CNetworking))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BProses, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nim)
                            .addComponent(Hp)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TNama)
                                .addComponent(TNim)
                                .addComponent(THp, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CmbProgramStudi, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CmbDaerahAsal, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(BProses)
                        .addGap(18, 18, 18)
                        .addComponent(BReset)
                        .addGap(18, 18, 18)
                        .addComponent(BKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nim)
                            .addComponent(TNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(THp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hp))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CmbProgramStudi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(CmbDaerahAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBPria)
                            .addComponent(CProgrammer)
                            .addComponent(CNetworking))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBWanita)
                            .addComponent(CDesain)
                            .addComponent(CMultimedia))))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(698, 636));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNamaActionPerformed

    private void TNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNimActionPerformed

    private void CmbProgramStudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbProgramStudiActionPerformed
        // TODO add your handling code here:
        CmbProgramStudi.getSelectedItem();
    }//GEN-LAST:event_CmbProgramStudiActionPerformed

    private void RBPriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBPriaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_RBPriaActionPerformed

    private void CmbProgramStudiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CmbProgramStudiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbProgramStudiMouseClicked

    private void BProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BProsesActionPerformed
        // TODO add your handling code here:
        namaMhs = TNama.getText();
        nim = TNim.getText();
        tlp = THp.getText();
        agama = CmbProgramStudi.getSelectedItem().toString();
       
         if(RBPria.isSelected())
        {
            jk = RBPria.getText();
        }
        else if(RBWanita.isSelected())
        {
            jk = RBWanita.getText();
        }
         
             if(CNetworking.isSelected())
        {
            minat = CNetworking.getText();
        }
        
        else if(CProgrammer.isSelected())
        {
            minat = CProgrammer.getText();
        }
        
        else if(CMultimedia.isSelected())
        {
            minat = CMultimedia.getText();
        }
        
        else if(CDesain.isSelected())
        {
            minat = CDesain.getText();
        }
             
        TOutput.setText("Nama\t:"+namaMhs+"\nNo.Hp\t:"+tlp+"\nAgama\t:"+agama+"\nGender\t:"+jk+"\nMinat\t:"+minat);
    }//GEN-LAST:event_BProsesActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void THpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_THpActionPerformed

    private void RBWanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBWanitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBWanitaActionPerformed

    private void CProgrammerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CProgrammerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CProgrammerActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        Nim.setText("");
        Hp.setText("");
        TOutput.setText("");
        gender.clearSelection();
    }//GEN-LAST:event_BResetActionPerformed

    private void BKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BKeluarActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void CmbDaerahAsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbDaerahAsalActionPerformed
        // TODO add your handling code here:
        CmbDaerahAsal.getSelectedItem();
        
    }//GEN-LAST:event_CmbDaerahAsalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BKeluar;
    private javax.swing.JButton BProses;
    private javax.swing.JButton BReset;
    private javax.swing.JCheckBox CDesain;
    private javax.swing.JCheckBox CMultimedia;
    private javax.swing.JCheckBox CNetworking;
    private javax.swing.JCheckBox CProgrammer;
    private javax.swing.JComboBox<String> CmbDaerahAsal;
    private javax.swing.JComboBox<String> CmbProgramStudi;
    private javax.swing.JLabel Hp;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nim;
    private javax.swing.JRadioButton RBPria;
    private javax.swing.JRadioButton RBWanita;
    private javax.swing.JTextField THp;
    private javax.swing.JTextField TNama;
    private javax.swing.JTextField TNim;
    private javax.swing.JTextArea TOutput;
    private com.jtattoo.plaf.aluminium.AluminiumDefaultTheme aluminiumDefaultTheme1;
    private com.jtattoo.plaf.aluminium.AluminiumLookAndFeel aluminiumLookAndFeel1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
